## Basic Configuration

baseurl = "https://nakabonne.com" 
#builddrafts = false
#canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Ryo Nakao"
title = "Ryo Nakao"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Ryo Nakao"
intro = "Software Engineer"
description = "@nakabonne"
authorimage = "icon.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Software Engineer"
keywords = "engineer,go,ruby,vim,unity,student"

## Social Accounts
[params.social]
github = "nakabonne"
#instagram = "nakabonne"
linkedin = "ryo-nakao-553529172"
twitter = "nakabonne"
facebook = "nakabonne"
#stackoverflow = "ryo-nakao"
email = "rodriguez.nak@gmail.com"

## Extras
[params.extra]
copyright = "Â© 2018. Ryo Nakao. [nakabonne](https://nakabonne.com)." 
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog(jp)"
    weight = 100
    identifier = "blog-jp"
    url = "http://nakawatch.hatenablog.com/"
[[menu.main]]
    name = "blog(en)"
    weight = 200
    identifier = "blog-en"
    url = "https://medium.com/@nakabonne"
[[menu.main]]
    name = "qiita"
    identifier = "qiita"
    weight = 300
    url = "https://qiita.com/nakabonne"
[[menu.main]]
    name = "speaker deck"
    identifier = "speaker deck"
    weight = 400
    url = "https://speakerdeck.com/nakabonne"
[[menu.main]]
    name = "wantedly"
    identifier = "wantedly"
    weight = 500
    url = "https://www.wantedly.com/users/18358896"
[[menu.main]]
    name = "app store"
    identifier = "app store"
    weight = 600
    url = "https://itunes.apple.com/jp/developer/ryo-nakao/id1140233971?l=en&mt=8"
[[menu.main]]
    name = "play store"
    identifier = "play store"
    weight = 700
    url = "https://play.google.com/store/apps/developer?id=Ryo+Nakao"
